import type { Medicine } from "./types";

export const MEDICINES: Medicine[] = [
  {
    id: "dolo-650",
    name: "Dolo 650",
    salt: "Paracetamol 650mg",
    brand: "Dolo",
    manufacturer: "Micro Labs Ltd",
    category: "otc",
    healthConcern: ["pain", "cold"],
    price: 32,
    mrp: 34.5,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: false,
    uses: "Relief from fever and mild to moderate pain including headache, toothache, and body ache.",
    howToUse: "Take 1 tablet every 6 hours as needed, with or after food. Do not exceed 4 tablets in 24 hours.",
    sideEffects: "Generally well tolerated. Rare: nausea, skin rash, allergic reaction.",
    safety: "Avoid alcohol. Consult a doctor if you have liver or kidney disease.",
    accent: "oklch(0.62 0.14 155)",
  },
  {
    id: "azithral-500",
    name: "Azithral 500",
    salt: "Azithromycin 500mg",
    brand: "Azithral",
    manufacturer: "Alembic Pharmaceuticals",
    category: "prescription",
    healthConcern: ["cold"],
    price: 92,
    mrp: 108,
    packSize: "Strip of 5 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
    uses: "Antibiotic for bacterial infections of the respiratory tract, skin, and ear.",
    howToUse: "Take one tablet daily, at the same time each day, for the duration prescribed.",
    sideEffects: "Nausea, diarrhoea, abdominal pain, headache.",
    safety: "Complete the full course even if you feel better. Not for viral infections.",
    accent: "oklch(0.53 0.08 190)",
  },
  {
    id: "metformin-500",
    name: "Glycomet 500",
    salt: "Metformin 500mg",
    brand: "Glycomet",
    manufacturer: "USV Pvt Ltd",
    category: "prescription",
    healthConcern: ["diabetes"],
    price: 24,
    mrp: 28,
    packSize: "Strip of 20 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
    uses: "Type 2 diabetes — helps control blood sugar levels.",
    howToUse: "Take with meals as prescribed. Do not crush or chew.",
    sideEffects: "Nausea, metallic taste, diarrhoea (usually settle within days).",
    safety: "Regular kidney function monitoring recommended.",
    accent: "oklch(0.6 0.1 230)",
  },
  {
    id: "telma-40",
    name: "Telma 40",
    salt: "Telmisartan 40mg",
    brand: "Telma",
    manufacturer: "Glenmark Pharmaceuticals",
    category: "prescription",
    healthConcern: ["cardiac"],
    price: 148,
    mrp: 175,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
    uses: "High blood pressure and cardiovascular protection.",
    howToUse: "One tablet once daily, at the same time each day.",
    sideEffects: "Dizziness, back pain, sinus congestion.",
    safety: "Do not stop suddenly. Not for use during pregnancy.",
    accent: "oklch(0.6 0.22 25)",
  },
  {
    id: "atorva-10",
    name: "Atorva 10",
    salt: "Atorvastatin 10mg",
    brand: "Atorva",
    manufacturer: "Zydus Cadila",
    category: "prescription",
    healthConcern: ["cardiac"],
    price: 78,
    mrp: 92,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
    uses: "Lowers cholesterol and reduces risk of heart disease.",
    howToUse: "Once daily at bedtime, with or without food.",
    sideEffects: "Muscle pain, mild digestive upset.",
    safety: "Periodic liver-function tests recommended.",
    accent: "oklch(0.53 0.08 190)",
  },
  {
    id: "cetzine",
    name: "Cetzine",
    salt: "Cetirizine 10mg",
    brand: "Cetzine",
    manufacturer: "Dr. Reddy's Laboratories",
    category: "otc",
    healthConcern: ["cold", "skin"],
    price: 42,
    mrp: 48,
    packSize: "Strip of 10 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: false,
    uses: "Relief from allergy symptoms, runny nose, sneezing, and itching.",
    howToUse: "One tablet once daily, preferably at bedtime.",
    sideEffects: "Mild drowsiness, dry mouth.",
    safety: "Avoid driving if drowsy. Not recommended in pregnancy without advice.",
    accent: "oklch(0.78 0.14 75)",
  },
  {
    id: "vicks-vaporub",
    name: "Vicks VapoRub",
    salt: "Camphor + Menthol + Eucalyptus Oil",
    brand: "Vicks",
    manufacturer: "Procter & Gamble",
    category: "otc",
    healthConcern: ["cold"],
    price: 105,
    mrp: 120,
    packSize: "50g jar",
    dosageForm: "Topical Ointment",
    prescriptionRequired: false,
    uses: "Relief from cough, blocked nose, and body ache due to cold.",
    howToUse: "Apply on chest, back, and throat. Do not apply on broken skin.",
    sideEffects: "Mild skin irritation in sensitive users.",
    safety: "For external use only. Keep away from eyes.",
    accent: "oklch(0.6 0.1 230)",
  },
  {
    id: "shelcal-500",
    name: "Shelcal 500",
    salt: "Calcium Carbonate + Vitamin D3",
    brand: "Shelcal",
    manufacturer: "Torrent Pharmaceuticals",
    category: "vitamins",
    healthConcern: [],
    price: 165,
    mrp: 195,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: false,
    uses: "Calcium and vitamin D supplementation for bone health.",
    howToUse: "One tablet daily after a meal, or as directed.",
    sideEffects: "Constipation, bloating (uncommon).",
    safety: "Do not exceed daily recommended dose.",
    accent: "oklch(0.62 0.14 155)",
  },
  {
    id: "revital-h",
    name: "Revital H",
    salt: "Multivitamin + Multimineral + Ginseng",
    brand: "Revital",
    manufacturer: "Sun Pharma",
    category: "vitamins",
    healthConcern: [],
    price: 289,
    mrp: 340,
    packSize: "Bottle of 30 capsules",
    dosageForm: "Capsule",
    prescriptionRequired: false,
    uses: "Daily nutritional support, energy, and stamina.",
    howToUse: "One capsule daily after breakfast.",
    sideEffects: "Rarely, mild stomach discomfort.",
    safety: "Not a substitute for a balanced diet.",
    accent: "oklch(0.78 0.14 75)",
  },
  {
    id: "cetaphil-cleanser",
    name: "Cetaphil Gentle Skin Cleanser",
    salt: "Non-soap surfactant blend",
    brand: "Cetaphil",
    manufacturer: "Galderma",
    category: "skincare",
    healthConcern: ["skin"],
    price: 415,
    mrp: 499,
    packSize: "250ml bottle",
    dosageForm: "Liquid Cleanser",
    prescriptionRequired: false,
    uses: "Daily gentle cleansing for sensitive, dry, or normal skin.",
    howToUse: "Apply to damp skin, massage, and rinse. Use morning and night.",
    sideEffects: "Very rare — mild irritation in ultra-sensitive skin.",
    safety: "Suitable for face and body. Avoid contact with eyes.",
    accent: "oklch(0.53 0.08 190)",
  },
  {
    id: "himalaya-baby-lotion",
    name: "Himalaya Baby Lotion",
    salt: "Olive oil + Almond oil",
    brand: "Himalaya",
    manufacturer: "Himalaya Wellness",
    category: "babycare",
    healthConcern: ["skin"],
    price: 175,
    mrp: 200,
    packSize: "200ml bottle",
    dosageForm: "Lotion",
    prescriptionRequired: false,
    uses: "Daily moisturization for delicate baby skin.",
    howToUse: "Apply gently on clean skin, twice a day.",
    sideEffects: "None reported.",
    safety: "For external use only.",
    accent: "oklch(0.62 0.14 155)",
  },
  {
    id: "bp-monitor",
    name: "Omron HEM-7120 BP Monitor",
    salt: "Digital blood pressure monitor",
    brand: "Omron",
    manufacturer: "Omron Healthcare",
    category: "devices",
    healthConcern: ["cardiac"],
    price: 1899,
    mrp: 2299,
    packSize: "1 device with cuff",
    dosageForm: "Device",
    prescriptionRequired: false,
    uses: "At-home monitoring of systolic/diastolic blood pressure and pulse.",
    howToUse: "Wrap cuff on upper arm, sit still, press start. See manual for details.",
    sideEffects: "Not applicable.",
    safety: "Do not use over injured skin. Batteries not included.",
    accent: "oklch(0.6 0.1 230)",
  },
  {
    id: "glucometer",
    name: "Accu-Chek Active Glucometer",
    salt: "Blood glucose meter kit",
    brand: "Accu-Chek",
    manufacturer: "Roche Diabetes Care",
    category: "devices",
    healthConcern: ["diabetes"],
    price: 1350,
    mrp: 1650,
    packSize: "1 meter + 10 strips",
    dosageForm: "Device",
    prescriptionRequired: false,
    uses: "Quick, accurate at-home blood glucose monitoring.",
    howToUse: "Insert test strip, apply blood drop, read result in seconds.",
    sideEffects: "Not applicable.",
    safety: "Use only compatible test strips.",
    accent: "oklch(0.6 0.22 25)",
  },
  {
    id: "pan-40",
    name: "Pan 40",
    salt: "Pantoprazole 40mg",
    brand: "Pan",
    manufacturer: "Alkem Laboratories",
    category: "prescription",
    healthConcern: ["digestion"],
    price: 118,
    mrp: 138,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
    uses: "Acid reflux, stomach ulcers, and heartburn.",
    howToUse: "One tablet, 30 minutes before breakfast.",
    sideEffects: "Headache, nausea, diarrhoea.",
    safety: "Long-term use requires medical review.",
    accent: "oklch(0.78 0.14 75)",
  },
  {
    id: "crocin-cold-flu",
    name: "Crocin Cold & Flu Max",
    salt: "Paracetamol + Phenylephrine + Caffeine",
    brand: "Crocin",
    manufacturer: "GSK Consumer Healthcare",
    category: "otc",
    healthConcern: ["cold", "pain"],
    price: 68,
    mrp: 78,
    packSize: "Strip of 10 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: false,
    uses: "Multi-symptom relief for cold, blocked nose, and fever.",
    howToUse: "One tablet every 6 hours as needed. Max 4 per day.",
    sideEffects: "Mild restlessness due to caffeine content.",
    safety: "Avoid other paracetamol products at the same time.",
    accent: "oklch(0.6 0.1 230)",
  },
  {
    id: "moov-cream",
    name: "Moov Pain Relief Cream",
    salt: "Diclofenac + Methyl salicylate + Menthol",
    brand: "Moov",
    manufacturer: "Reckitt Benckiser",
    category: "otc",
    healthConcern: ["pain"],
    price: 145,
    mrp: 165,
    packSize: "50g tube",
    dosageForm: "Topical Cream",
    prescriptionRequired: false,
    uses: "Relief from back pain, joint pain, and sprains.",
    howToUse: "Apply a thin layer to affected area 3–4 times a day.",
    sideEffects: "Mild burning sensation in some users.",
    safety: "For external use only. Do not apply to broken skin.",
    accent: "oklch(0.6 0.22 25)",
  },
];

export function getMedicine(id: string): Medicine | undefined {
  return MEDICINES.find((m) => m.id === id);
}

export const CATEGORIES: { id: string; label: string; description: string }[] = [
  { id: "prescription", label: "Prescription Medicines", description: "Rx-only, verified by our pharmacist" },
  { id: "otc", label: "OTC Medicines", description: "Common over-the-counter essentials" },
  { id: "skincare", label: "Skin Care", description: "Cleansers, moisturisers, dermatology" },
  { id: "vitamins", label: "Vitamins & Supplements", description: "Daily nutrition support" },
  { id: "babycare", label: "Baby Care", description: "Gentle, tested for little ones" },
  { id: "devices", label: "Health Devices", description: "BP, glucose, thermometers & more" },
];

export const HEALTH_CONCERNS: { id: string; label: string }[] = [
  { id: "diabetes", label: "Diabetes" },
  { id: "cardiac", label: "Cardiac Care" },
  { id: "skin", label: "Skin" },
  { id: "pain", label: "Pain Relief" },
  { id: "cold", label: "Cold & Fever" },
  { id: "digestion", label: "Digestion" },
];
