import type { Medicine } from "./types";

export const MEDICINES: Medicine[] = [
  {
    id: "dolo-650",
    name: "Dolo 650",
    salt: "Paracetamol 650mg",
    brand: "Dolo",
    mrp: 34.5,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: false,
  },
  {
    id: "azithral-500",
    name: "Azithral 500",
    salt: "Azithromycin 500mg",
    brand: "Azithral",
    mrp: 108,
    packSize: "Strip of 5 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
  },
  {
    id: "metformin-500",
    name: "Glycomet 500",
    salt: "Metformin 500mg",
    brand: "Glycomet",
    mrp: 28,
    packSize: "Strip of 20 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
  },
  {
    id: "telma-40",
    name: "Telma 40",
    salt: "Telmisartan 40mg",
    brand: "Telma",
    mrp: 175,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
  },
  {
    id: "atorva-10",
    name: "Atorva 10",
    salt: "Atorvastatin 10mg",
    brand: "Atorva",
    mrp: 92,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
  },
  {
    id: "cetzine",
    name: "Cetzine",
    salt: "Cetirizine 10mg",
    brand: "Cetzine",
    mrp: 48,
    packSize: "Strip of 10 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: false,
  },
  {
    id: "vicks-vaporub",
    name: "Vicks VapoRub",
    salt: "Camphor + Menthol + Eucalyptus Oil",
    brand: "Vicks",
    mrp: 120,
    packSize: "50g jar",
    dosageForm: "Topical Ointment",
    prescriptionRequired: false,
  },
  {
    id: "shelcal-500",
    name: "Shelcal 500",
    salt: "Calcium Carbonate + Vitamin D3",
    brand: "Shelcal",
    mrp: 195,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: false,
  },
  {
    id: "revital-h",
    name: "Revital H",
    salt: "Multivitamin + Multimineral + Ginseng",
    brand: "Revital",
    mrp: 340,
    packSize: "Bottle of 30 capsules",
    dosageForm: "Capsule",
    prescriptionRequired: false,
  },
  {
    id: "cetaphil-cleanser",
    name: "Cetaphil Gentle Skin Cleanser",
    salt: "Non-soap surfactant blend",
    brand: "Cetaphil",
    mrp: 499,
    packSize: "250ml bottle",
    dosageForm: "Liquid Cleanser",
    prescriptionRequired: false,
  },
  {
    id: "himalaya-baby-lotion",
    name: "Himalaya Baby Lotion",
    salt: "Olive oil + Almond oil",
    brand: "Himalaya",
    mrp: 200,
    packSize: "200ml bottle",
    dosageForm: "Lotion",
    prescriptionRequired: false,
  },
  {
    id: "bp-monitor",
    name: "Omron HEM-7120 BP Monitor",
    salt: "Digital blood pressure monitor",
    brand: "Omron",
    mrp: 2299,
    packSize: "1 device with cuff",
    dosageForm: "Device",
    prescriptionRequired: false,
  },
  {
    id: "glucometer",
    name: "Accu-Chek Active Glucometer",
    salt: "Blood glucose meter kit",
    brand: "Accu-Chek",
    mrp: 1650,
    packSize: "1 meter + 10 strips",
    dosageForm: "Device",
    prescriptionRequired: false,
  },
  {
    id: "pan-40",
    name: "Pan 40",
    salt: "Pantoprazole 40mg",
    brand: "Pan",
    mrp: 138,
    packSize: "Strip of 15 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: true,
  },
  {
    id: "crocin-cold-flu",
    name: "Crocin Cold & Flu Max",
    salt: "Paracetamol + Phenylephrine + Caffeine",
    brand: "Crocin",
    mrp: 78,
    packSize: "Strip of 10 tablets",
    dosageForm: "Tablet",
    prescriptionRequired: false,
  },
  {
    id: "moov-cream",
    name: "Moov Pain Relief Cream",
    salt: "Diclofenac + Methyl salicylate + Menthol",
    brand: "Moov",
    mrp: 165,
    packSize: "50g tube",
    dosageForm: "Topical Cream",
    prescriptionRequired: false,
  },
];

export function getMedicine(id: string): Medicine | undefined {
  return MEDICINES.find((m) => m.id === id);
}

export const CATEGORIES: { id: string; label: string; description: string }[] = [
  { id: "prescription", label: "Prescription Medicines", description: "Rx-only, verified by our pharmacist" },
  { id: "otc", label: "OTC Medicines", description: "Common over-the-counter essentials" },
  { id: "skincare", label: "Skin Care", description: "Cleansers, moisturisers, dermatology" },
  { id: "vitamins", label: "Vitamins & Supplements", description: "Daily nutrition support" },
  { id: "babycare", label: "Baby Care", description: "Gentle, tested for little ones" },
  { id: "devices", label: "Health Devices", description: "BP, glucose, thermometers & more" },
];

export const HEALTH_CONCERNS: { id: string; label: string }[] = [
  { id: "diabetes", label: "Diabetes" },
  { id: "cardiac", label: "Cardiac Care" },
  { id: "skin", label: "Skin" },
  { id: "pain", label: "Pain Relief" },
  { id: "cold", label: "Cold & Fever" },
  { id: "digestion", label: "Digestion" },
];
